### PR TITLE
Automatic fixes on Swift 5 and Xcode 10.2.1.

### PR DESCRIPTION
**Pull request by lk251**

### CODE REVIEW

**Review by SCKelemen — APPROVED** [review]
LGTM

**Comment by lk251** [comment]
Cheers, and I apologize for the comment on 7e33f5a "Print username from delegate method in viewcontroller." which is clearly meant for another commit, I have no idea what happened there.
(7e33f5a does no such thing, it's another syntax update for Swift 5)

**Comment by SCKelemen** [comment]
> Cheers, and I apologize for the comment on [7e33f5a](https://github.com/bhlvoong/LBTAComponents/commit/7e33f5a04c9eccab5d27ea177cb756e75a00e715) "Print username from delegate method in viewcontroller." which is clearly meant for another commit, I have no idea what happened there.
> ([7e33f5a](https://github.com/bhlvoong/LBTAComponents/commit/7e33f5a04c9eccab5d27ea177cb756e75a00e715) does no such thing, it's another syntax update for Swift 5)

You can update the commit message for any commit using the hash:
```sh
git rebase -i 7e33f5a^
```

If you want to update the commit message of only the last commit, you can use:
```sh
git commit --amend
```

I'm not telling you to do this. I'm just providing information in the case you are interested.

**Comment by bhlvoong** [comment]
I just updated everything to use Swift 5.0.  Latest release of 1.1 is now compatible.

**Pull request closed without merging**
