### PR TITLE
Update to swift 4.2

### PR DESCRIPTION
**Pull request by jesus-rod**
Swift 4.2 update 🌝

### CODE REVIEW

**Comment by ibakurov** [comment]
Please, merge this branch.

**Comment by nicodioso** [comment]
please merge this sir Brian

**Comment by dubeboy** [comment]
Please merge , or provide a reason of not merging

**Comment by bhlvoong** [comment]
Everything has been updated to Swift 5 now.  I also recommend using LBTATools instead, I will be deprecating LBTAComponents.

**Pull request closed without merging**
